services:
  zoo_scheduling_app:
    build:
      args:
        user: Tanvir
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: zoo-scheduling
    container_name: zoo-scheduling-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./.docker/app/php-fpm.ini:/usr/local/etc/php/conf.d/99-app.ini
    depends_on:
      - zoo_scheduling_database
    links:
      - zoo_scheduling_database
    networks:
      - zoo-scheduling-network
  zoo_scheduling_nginx:
    image: nginx:alpine
    container_name: zoo-scheduling-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/
    networks:
      - zoo-scheduling-network
    depends_on:
      - zoo_scheduling_database
      - zoo_scheduling_pma
  zoo_scheduling_database:
    image: mariadb
    container_name: zoo-scheduling-database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - zoo-scheduling-network
  zoo_scheduling_pma:
    image: phpmyadmin
    container_name: zoo-scheduling-pma
    restart: always
    tty: true
    depends_on:
      - zoo_scheduling_database
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: zoo_scheduling_database
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 2048M
    networks:
      - zoo-scheduling-network
networks:
  zoo-scheduling-network:
    driver: bridge
